### ISSUE TITLE
Have you tested the CPU speed

### ISSUE THREAD

**Issue by Belinda-great** [songwsx/RFSong-779#4]

**Comment by Belinda-great** [comment]
Thank you for your contributions. Have you tested the CPU speed for epoches_114.pth?

**Comment by songwsx** [comment]
> Thank you for your contributions. Have you tested the CPU speed for epoches_114.pth?

Sorry, I only tested it on the GPU. And the network is also designed for the GPU.

**Comment by Belinda-great** [comment]
Thank you!
